### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'url')

### ISSUE THREAD

**Issue by undefined-hestudio** [hestudio-community/bing-wallpaper-get#29]
```
[2023-12-08 00:38:01] heStudio BingWallpaper Get version: 1.4.0-beta.1
[2023-12-08 00:38:06] An external file has been imported.
[2023-12-08 00:38:06] The api configuration has been loaded.
/root/test/node_modules/.pnpm/hestudio-bingwallpaper-get@1.4.0-beta.1/node_modules/hestudio-bingwallpaper-get/get.js:233
if (typeof hbwgConfig.external !== 'undefined' && typeof hbwgConfig.external.bingsrc.url === 'string') hbwgConfig.apiconfig.bingsrc = String(hbwgConfig.external.bingsrc.url)
                                                                                     ^

TypeError: Cannot read properties of undefined (reading 'url')
    at Object.<anonymous> (/root/test/node_modules/.pnpm/hestudio-bingwallpaper-get@1.4.0-beta.1/node_modules/hestudio-bingwallpaper-get/get.js:233:86)
    at Module._compile (node:internal/modules/cjs/loader:1256:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
    at Module.load (node:internal/modules/cjs/loader:1119:32)
    at Module._load (node:internal/modules/cjs/loader:960:12)
    at Module.require (node:internal/modules/cjs/loader:1143:19)
    at require (node:internal/modules/cjs/helpers:110:18)
    at Object.<anonymous> (/root/test/server.js:1:1)
    at Module._compile (node:internal/modules/cjs/loader:1256:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)

Node.js v18.16.1
```

**Comment by undefined-hestudio** [comment]
#18 

repair it on `1.4.0-beta.2`
